name: DeathExplosion
version: '1.3.Alpha'
main: com.outlook.fivedollagobby.DeathExplosion
api-version: '1.20'

commands:
  deselectparticle:
    description: Opens the GUI to select explosion particles
    usage: /deselectparticle

permissions:
  dexplode.gui.access:
    description: Allows access to the particle selection GUI
    default: op
  dexplode.explode:
    description: Allows player to explode on death
    default: false
  dexplode.explode.EXPLOSION_HUGE:
    description: Allows using EXPLOSION_HUGE particles
    default: op
  dexplode.explode.FLAME:
    description: Allows using FLAME particles
    default: op
  dexplode.explode.SMOKE_LARGE:
    description: Allows using SMOKE_LARGE particles
    default: op
  dexplode.explode.LAVA:
    description: Allows using LAVA particles
    default: op
  dexplode.explode.HEART:
    description: Allows using HEART particles
    default: op
  dexplode.explode.WATER_DROP:
    description: Allows using WATER_DROP particles
    default: op
  dexplode.explode.VILLAGER_HAPPY:
    description: Allows using VILLAGER_HAPPY particles
    default: op
  dexplode.explode.FIREWORKS_SPARK:
    description: Allows using FIREWORKS_SPARK particles
    default: op
  dexplode.explode.MAGIC_CRIT:
    description: Allows using MAGIC_CRIT particles
    default: op
